### ISSUE TITLE
Sugestão de Melhoria

### ISSUE THREAD

**Issue by ltuchoa** [beacarlos/Integrate#1]
Larissa / Eduardo

**Arquivo:**
main.swift

**Melhoria:**
Criar uma função ou estrutura para criação da interface para organizar melhor o código.
Criar um loop infinito para que o programa só fechasse quando o usuário quisesse, para evitar ficar reabrindo caso o usuário deseje calcular várias integrais.

**Comment by ronaldogomes96** [comment]
Muito obrigado pelo feedback, as duas novas funcionalidades propostas foram implementadas!!
