### ISSUE TITLE
Melhorar a forma de receber as funções matemáticas

### ISSUE THREAD

**Issue by NobreMateus** [beacarlos/Integrate#2]
O programa está esperando uma função matemática com cada elemento separado por " ". Isso pode ser prejudicial em alguns casos para o usuário. Uma maneira de melhorar isso seria fazendo a separação dos elementos através dos próprios símbolos matemáticos. 

Primeiro dando um replace para substituir todos os espacos por nada, tipo: "". 

Depois ir percorrendo o array procurando por símbolos matemáticos. Se for um símbolo do tipo * (  / ... ele ja pega aquele valor, pq nunca haverá uma operação com dois caracteres. Porem, se for um numero do tipo numérico:  1 2 3 4... ele precisaria ficar verificando o caracter mais a direita pra ver se é numero ou não e ir appendando até a próxima posição nao ser caracter numérico,  já que um numero pode ter 2 caracteres ou mais.

Dessa forma, o programa poderia receber de entrada tanto:  "2 x" como "2x"  ou "2          x" e daria no mesmo

**Comment by ronaldogomes96** [comment]
Muito obrigado pelo feedback, ele é muito importante. Esse realmente era um problema que enfrentamos no começo e a melhor solução que tínhamos achado no momento era esse, porem concordo que não era o ideal. Ja foi feito um pull request que foi aceito que resolve esse problema de digitar com espaços, usando uma lib chamado NSExpression, podendo agora inclusive digitar com parênteses dentro de parênteses!.
Sinta-se convidado a testar o script novamente e caso queira abrir uma nova issue com algo novo encontrado, agradecemos!!
