### ISSUE TITLE
Tratamento dos intervalos da integral

### ISSUE THREAD

**Issue by talesconrado** [beacarlos/Integrate#3]
**Dupla**:
@FelipeSantana16 @talesconrado

**Arquivo**:
main.swift

**Sugestão**:
No trecho onde se pedem os intervalos da integral, não usar o forced unwrapping para evitar crashs inesperados. Tratar os inputs antes de atribui-los ao ```range```.

Antes:
```
intervalos = input.components(separatedBy: ", ")
    if intervalos.count == 2 {
        range = Double(intervalos[0])! ... Double(intervalos[1])!
```

Depois:

```
intervalos = input.components(separatedBy: ", ")
   if intervalos.count == 2{
       guard let primeiroIntervalo = Double(intervalos[0]) else {
             print("Primeiro intervalo inválido.")
             // tratar erro
       }
       guard let segundoIntervalo = Double(intervalos[1]) else {
             print("Segundo intervalo inválido.")
             // tratar erro
       }
       range = primeiroIntervalo ... segundoIntervalo
```

**Comment by ronaldogomes96** [comment]
Muito obrigado pelo feedback e mais ainda pelo código proposto. Essa forma de inserir intervalos foi adicionada no final e acabamos não lidando com possíveis erros que poderiam acontecer nesta parte do código. Parabéns pela ideia de separar os intervalos em duas variáveis diferentes, isso ajudou ate no tratamento de um outro erro. As funcionalidades propostas foram implementadas!
