### ISSUE TITLE
Tratamento de erros

### ISSUE THREAD

**Issue by helainepontes** [beacarlos/Integrate#4]
Dupla:
Hiago 
Helaine

Arquivo:
main.swift

Sugestão:
Fazer o tratamento de erros, para se o usuário digitar algo errado mostrar algum tipo de mensagem e interromper o fluxo do programa, para o usuário digitar novamente da forma correta. Por exemplo, eu digitei a seguinte sentença ( x + 10 ) * 2, ele não me retornou nenhum erro, porém fiquei esperando o resultado, o programa não quebrou, mas também não mostrou o resultado.

**Comment by helainepontes** [comment]
Um exemplo simples de como fazer.
Antes:
`    intervalos = input.components(separatedBy: ", ")
    if intervalos.count == 2 {
        range = Double(intervalos[0])! ... Double(intervalos[1])!
        print("""
            
        Você digitou: \(input)
            
        -------------------------------------------------------
        Deseja alterar os intervalos?
        ✅  Sim? Então digite novamente a sua equação novamente
        ❌  Não? Então digite "quit" ou "q".
        """)
    }`

Depois:

`    intervalos = input.components(separatedBy: ", ")
    if intervalos.count == 2 {
        range = Double(intervalos[0])! ... Double(intervalos[1])!
        print("""
            
        Você digitou: \(input)
            
        -------------------------------------------------------
        Deseja alterar os intervalos?
        ✅  Sim? Então digite novamente a sua equação novamente
        ❌  Não? Então digite "quit" ou "q".
        """)
    }else{
        print("Entrada inválida")
    }`

**Comment by ronaldogomes96** [comment]
Muito obrigado pelo feedback, ele é bastante importante. Fizemos alguns tratamentos de possíveis erros, tanto na digitação da função quanto dos intervalos. Ja subimos o código com essas correções, sinta-se convidada pra continuar testando e relatar em novas issues possíveis erros ou melhorias. Obrigado pela ajuda!!
