### ISSUE TITLE
Primeira verificação da function integral

### ISSUE THREAD

**Issue by jjoaosilva** [beacarlos/Integrate#5]
Dentro do while principal da function, existe uma verificação de quando é o primeiro item da lista, o que será verificado durante o loop todo. Para melhorar a performance, essa verificação, que é especifica e única, poderia ser realizada uma única vez fora no loop.

**Antes**
```
public func integral(fullFunction: [Any], x: Double) -> Double {
    var variable: Double = 0.0
    var i = 0
    
    // Converte números para double, operadores e variáveis.
    while fullFunction.count > i {
        let current_element = fullFunction[i]
        
        if i == 0 {
            variable = convertToDouble(element: current_element, x: x)
           i += 1
        }
        else if let mathOperator = current_element as? String, mathOperations.contains(mathOperator) == true {
```

**Depois**
```
public func integral(fullFunction: [Any], x: Double) -> Double {
    var variable: Double = 0.0
    var i = 1
    
    variable = convertToDouble(element: fullFunction[0], x: x)
  
    // Converte números para double, operadores e variáveis.
    while fullFunction.count > i {
        let current_element = fullFunction[i]
        
        if let mathOperator = current_element as? String, mathOperations.contains(mathOperator) == true {
```

**Comment by ronaldogomes96** [comment]
Muito obrigado pelo feedback. Realmente não tínhamos percebido isso, é uma melhoria de performance importante e ate implementaríamos, porem voce mesmo substitui toda essa função que nem existe mais por outra bem melhor!! 
Obrigado por participar tão ativamente do nosso código e sinta-se livre pra continuar contribuindo :D
