### ISSUE TITLE
Sugestão de Modularização

### ISSUE THREAD

**Issue by CrisCoutinho** [beacarlos/Integrate#6]
**Dupla**: Cristiano Coutinho  e Pedro Sousa

**Sugestão:**
Separar em dois novos arquivos, um para a entrada input/output e a outra para o cálculo para chamá-los na main.swift .

**Comment by ronaldogomes96** [comment]
Muito obrigado pelo feedback. A modularização do projeto foi implementada como proposto, melhorando bastante a organização geral. Obrigado pela sugestão!!
